### ISSUE TITLE
--eval problem

### ISSUE THREAD

**Issue by zhangkexin1126** [salesforce/CoST#1]
Thank for sharing the code.
I found that the value of parameter "padding" in forecasting.py (line 24 or  the first line in function eval_forecasting()) should be equal to args.max-train-length, if not, the evaluation process is not available.

**Comment by gorold** [comment]
Thanks for catching that, it was hardcoded into the script since all experiments in the paper used that same setting.

**Comment by msonah** [comment]
> Thank for sharing the code. I found that the value of parameter "padding" in forecasting.py (line 24 or the first line in function eval_forecasting()) should be equal to args.max-train-length, if not, the evaluation process is not available.

The author set the parameter 'kernels' (Kernel sizes for mixture of AR experts module) in the code to 'None', when I run the code, it will report an error (Rearrange can't be applied to an empty list), please ask' How should kernels' be set up, may you give me some advice?

**Comment by gorold** [comment]
Fixed issue: 3c4e765
