### ISSUE TITLE
TypeError: Rearrange can't be applied to an empty list

### ISSUE THREAD

**Issue by shlee-home** [salesforce/CoST#10]
Hello, I'm interested in your research.

So, I tried to run your code as you mentioned home:
       python train.py ETTh1 output --archive forecast_csv --batch-size 256 --repr-dims 320 --gpu 0 --epochs 200
But, I got following error:
       TypeError: Rearrange can't be applied to an empty list

How can I solve this problem?
Thank you.

**Comment by gorold** [comment]
Hi, you could try running one of the provided scripts `./scripts/ETT_CoST.sh` (might need to edit permissions first by `chmod u+x scripts/`). If that still does not work, I would need to see the whole stack trace to know what the problem is.

**Comment by shlee-home** [comment]
Oh, thank u.
But, if possible, could you give me a detailed example of running code (dataset: ETTh1)? 
I wonder that the additional setting of parameters, including kernels, epochs, and iters, is nesseary. (In 'readme' file, there are <dataset_name>, <run_name>, <archive>, <batch_size>, <repr_dims>, <gpu>, and <eval>. However, in 'train' code, default of other parameters is none.)
