### ISSUE TITLE
Some questions about replication

### ISSUE THREAD

**Issue by renmada** [salesforce/CoST#15]
- There is a "archive" option in args, here is my unstanding "forecast_csv"="Multivariate forecasting" and "forecast_csv_univar"="Univariate forecasting"(Results show in Table 1 and Table 7). Is it correct?
- How to run CoST on feature-based approach ? (Results show in Table 8)

**Comment by gorold** [comment]
Yup, thats right. CoST is a feature-based approach. The term feature-based approach in the paper is to differentiate between 2-stage representation learning methods and end-to-end forecasting methods.
