### ISSUE TITLE
A little confused about Trend Feature Disentangler

### ISSUE THREAD

**Issue by Lip-Z** [salesforce/CoST#18]
Think your for your brilliant  job. Having read your guys paper, but didn't get the Trend Feature Disentangler, in the paper there is a formula about it which is
```
V (T ) = AvePool(V~ (T;0); V~ (T;1); : : : ; V~ (T;L)) 
```
when i run it in my IDE, found it is more like vertical connection conv block, and where is the AvgPool layer?
hope to get your help, and really appreciate your answer.

**Comment by gorold** [comment]
Average pooling occurs [here](https://github.com/salesforce/CoST/blob/afc26aa0239470f522135f470861a1c375507e84/models/encoder.py#L154).

**Comment by Lip-Z** [comment]
Thanks, I got it
