### ISSUE TITLE
'--kernels' problem

### ISSUE THREAD

**Issue by msonah** [salesforce/CoST#4]
Thank for sharing the code.
You set the parameter 'kernels' (Kernel sizes for mixture of AR experts module) in the code to 'None', when I run the code, it will report an error (Rearrange can't be applied to an empty list), please ask' How should kernels' be set up, may you give me some advice?
Looking forward to your reply！

**Comment by gorold** [comment]
Thanks for the interest in our work! the kernels parameter can be set to a list of ints. Pleases check the scripts folder on how to use this parameter.
